### ISSUE TITLE
Cache not working on Android (simulator)

### ISSUE THREAD

**Issue by fumixia** [echowaves/expo-cached-image#10]
Hey!

Currently, we're implementing this package to cache our images on a social wall. All of this works perfectly on iOS but whenever we launch the app on the Android Simulator, the cached images won't load or cache at all (it seems at least)

We have a custom Image component where we provide the required props like so:
```
<Image
        resizeMode="cover"
        source={{
          uri,
        }}
        cacheKey={id}
        style={{
          width: imageContainerWidth,
          height: customHeight ?? imageContainerWidth * (height / width),
        }}
      />
```

And within this Image component we render it as follows:
```
export const Image = (props: ImageProps) => {
  const { source: rawSource, cacheKey, size } = props
  const source = appendSizeToUrl(rawSource, size)
  // If the source is a number it means it's a client-side "require" for a file
  // So, if the image exists on the client, we don't need to cache it.
  // Also, only cache the image if a cache key has been provided.
  if (!cacheKey || typeof source === "number") {
    return <RNImage {...props} />
  }

  return <ExpoCachedImage {...props} cacheKey={`${cacheKey}`} />
}
```

RNImage in this case is the default react native image component.
If I remove the cacheKey it, of course, uses the default rn image component, and the images load, but once I provide a cacheKey they will stop working on Android.

Do more people have this issue, or am I missing something here?

**Comment by dmitryame** [comment]
It seems to work just fine for me on Android emulator -- you should not need to perform special tricks (conditional logic), it should just work out of the box. The component is simple enough -- nothing really should work different on Android vs iOS.
I do have to admit, it took me some effort to find the right combination of emulator/API_Version to make it work, but that's more of an emulator stability question. I got it to work on Pixel XL API 32. Hope it helps. Let me know your findings.

**Comment by dmitryame** [comment]
Have you tried to re-produce this issue on other environments? If you tell me how I can reliably reproduce it -- I can look into it. So far everything I try -- works for me.

**Comment by dmitryame** [comment]
You can also try to play with recently added `placeholderContent` and `expiresIn` to better understand when your issue may occur in the life cycle of the component.

**Comment by ValeriiaShur** [comment]
Hey!

I might be experiencing similar issue. I noticed that my Android physical device does not load images even though all URIs are well provided and can be seen on iOS device+simulator. After looking up and seeing this closed issue, I tried to use `<CachedImage />` separately from my app in [Expo CachedImage Example](https://snack.expo.dev/@valeriiashur/expo-cachedimage-example). As you can see, the Android simulator loads up only certain URIs.

I am not sure if this is also the case for @fumixia ?

But maybe someone here could help to figure out how to fix it?

**Comment by dmitryame** [comment]
If you try to copy paste url like the one you have in your example https://images.pexels.com/photos/3680219/pexels-photo-3680219.jpeg?cs=srgb&dl=pexels-lukas-rodriguez-3680219.jpg&fm=jpg into the browser, instead of rendering the image it will try to download it as file. Have you tried to simplify the url to maybe only https://images.pexels.com/photos/3680219/pexels-photo-3680219.jpeg -- this works in the browser and as such should work with expo-cached-image out of the box. 
You can also try to experiment with headers (see the documentation) as well as with expiresIn .
