### ISSUE TITLE
doesn't work on expo SDK 45

### ISSUE THREAD

**Issue by vbylen** [echowaves/expo-cached-image#11]
When the remote url is not yet in the cache, I just get an error that the image could not be found in the cache.

I would expect that `<CachedImage/>` will automatically fetch the remote url if the cache is found empty.

Instead an empty `<CachedImage/>` is displayed.

Please let me know if I'm missing something.

**Comment by dmitryame** [comment]
I'm using it with sdk 45 and it works, can you provide some more context here? iOS, Android, physical devise, emulator? Can you copy paste the exact message? Have you upgraded expo-cached-image to the latest version 45.1.1?

**Comment by dmitryame** [comment]
Can you share some examples of the image URL's that do not work for you?

**Comment by vbylen** [comment]
Both simulator and physical device, android and ios.

I'm on the latest version.

Here's an example `https://i.pravatar.cc/1000?u=4b170797-abe3-5465-af48-7694dtr43a8ca`.

I'll try to post the exact error message here hopefully later today.

**Comment by dmitryame** [comment]
<img width="233" alt="iPhone_13_Pro_Max" src="https://user-images.githubusercontent.com/14113/181668516-92a4f7ef-7090-432c-8ace-607568014fb3.png">
It works for me.
See sample projects https://github.com/echowaves/test-expo-cached-image/blob/main/App.js#L11
What are you using for cacheKey? Make sure the key is rather simple.
This will work:

```
cacheKey={`4b170797-abe3-5465-af48-7694dtr43a8ca`}
```

Something like this will not:

```         
cacheKey={`https://i.pravatar.cc/1000?u=4b170797-abe3-5465-af48-7694dtr43a8ca`}
```

**Comment by vbylen** [comment]
That was indeed the problem. I went with something simpler and it works. Thank you sir.
