### ISSUE TITLE
SDK46 - IOS simulator error: Could not find image

### ISSUE THREAD

**Issue by SohelIslamImran** [echowaves/expo-cached-image#14]
![image](https://user-images.githubusercontent.com/76745339/186975047-73532b16-f884-444d-8680-874293bf0414.png)
![image](https://user-images.githubusercontent.com/76745339/186975055-114696d4-7e10-4073-a322-434f9cc83bb8.png)

**Comment by dmitryame** [comment]
What value do you use for the cacheKey?
It should be rather simple formatted value, like an ID, or UUID. If it's complex and contains special characters, it may not be able to map it to the file system URI.

**Comment by SohelIslamImran** [comment]
```js
const getCacheKey = (id, url) => id + url.split("&token=")[1];
...
<CachedImage
      style={style}
      cacheKey={`avatar-${getCacheKey(
        userId,
        firebaseStoreageImageURL
      )}`}
      source={{ uri: firebaseStoreageImageURL }}
      placeholderContent={
        <Image
          style={style}
          source={require("../../../../assets/defaultProfilePhoto.jpg")}
        />
      }
    />
```

**Comment by dmitryame** [comment]
Can you console.log(`avatar-${getCacheKey(userId, firebaseStorageImageURL)}`) and post the value here?

**Comment by dmitryame** [comment]
can't you use avatar-${userId} for cacheKey?
```
<CachedImage
  style={style}
  cacheKey={`avatar-${userId}`}
  source={{ uri: firebaseStorageImageURL }}
  placeholderContent={
    <Image
      style={style}
      source={require("../../../../assets/defaultProfilePhoto.jpg")}
    />
  }
/>
```
