### ISSUE TITLE
Always showing the placeholderContent.

### ISSUE THREAD

**Issue by SohelIslamImran** [echowaves/expo-cached-image#15]
Always showing the placeholderContent.

![image](https://user-images.githubusercontent.com/76745339/193700844-03962261-1347-4c8e-bb36-abaa527095ac.png)

**Comment by dmitryame** [comment]
Show me some code please...

**Comment by SohelIslamImran** [comment]
```js
<CachedImage
  style={style}
  cacheKey={avatarCacheKey}
  source={{ uri: currentMessage.user.avatar }}
  placeholderContent={
  <Image
      style={style}
      source={require("../../assets/defaultProfilePhoto.jpg")}
    />}
/>
```

**Comment by dmitryame** [comment]
cacheKey and uri have to be strings, try something like this:
```
<CachedImage
  style={style}
  cacheKey={`${avatarCacheKey}`}
  source={{ uri: `${currentMessage.user.avatar}` }}
  placeholderContent={
  <Image
      style={style}
      source={require("../../assets/defaultProfilePhoto.jpg")}
    />}
/>
```
If that does not help, can you share here the output of console.log for avatarCacheKey and currentMessage.user.avatar

**Comment by SohelIslamImran** [comment]
![image](https://user-images.githubusercontent.com/76745339/193713625-624514f5-c8db-4be3-8df3-b65dd5a50379.png)
![image](https://user-images.githubusercontent.com/76745339/193713631-27f5edf4-73c6-43e8-bd94-062fab3957ee.png)

**Comment by dmitryame** [comment]
Have you tried wrapping up the cacheKey value
```
`${avatarCacheKey}`
```

also, try to use more basic element in placeholder, like <Text/> to see if it works.
