### ISSUE TITLE
ActivityIndicator only..

### ISSUE THREAD

**Issue by playset** [echowaves/expo-cached-image#16]
Hi, i observed that it possible doesnt work if link is too long

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/57511636/198857758-50c4bc98-e2f2-4974-b055-e8e8d7742735.png">

**Comment by playset** [comment]
img link for example: https://glasulvietii.ro/wp-content/uploads/2022/10/am-facut-deja-fericiti-sapte-copii-%20[Dan%20Damaschin%20-%20Glasul%20Vietii]-e1666852603711-300x169.jpg

**Comment by dmitryame** [comment]
Can you check what's the value of your key?
console.log(\`${element.id}-thumbHome\`)

**Comment by playset** [comment]
> 

<img width="1351" alt="image" src="https://user-images.githubusercontent.com/57511636/198858053-46ef0e1c-5120-4770-b4ac-a193924e0ade.png">

**Comment by playset** [comment]
> Can you check what's the value of your key? console.log(`${element.id}-thumbHome`)

it's all good with keys.. i tried with short image link and it's worked.. idk maybe because it contains spaces %20 in link, or symbol like this ] and this [

**Comment by dmitryame** [comment]
CachedImage is actually not doing anything fancy, it's using `downloadResumable.downloadAsync` from expo FileSystem https://docs.expo.dev/versions/latest/sdk/filesystem/#filesystemdownloadasyncuri-fileuri-options
They must have some requirements for the URI's.

**Comment by dmitryame** [comment]
I'd say, generally speaking, it's probably a good idea to keep your structure of the URI as simple as possible and avoid special characters and spaces.

**Comment by dmitryame** [comment]
There are some similar reports of react-native Image crashing for the URI's that contain special characters:
https://www.reddit.com/r/reactnative/comments/odljln/image_component_crashes_if_url_has_special/
Try to avoid it as the common sense suggest it's not a good idea.

**Comment by playset** [comment]
> There are some similar reports of react-native Image crashing for the URI's that contain special characters: https://www.reddit.com/r/reactnative/comments/odljln/image_component_crashes_if_url_has_special/ Try to avoid it as the common sense suggest it's not a good idea.

thank you for response, yes.. i have like 5000 images like this in project which i make now. Thanks again

**Comment by dmitryame** [comment]
I bet, if you try to use react-native <Image>, you will get the same results for your URI's. 
Does not seem I can do much to help here, sorry. Will be closing this issue, let me know if you have some ideas what I can do to help.
