### ISSUE TITLE
Can I preload files with the cache manager from the web?

### ISSUE THREAD

**Issue by shamoons** [echowaves/expo-cached-image#18]

**Comment by dmitryame** [comment]
Can you share some code?

**Comment by shamoons** [comment]
```
  useEffect(() => {
    posts.forEach((post) => {
      post.media_attachments.forEach(async (media) => {
        try {
          await CacheManager.addToCache({
            file: media.url,
            id: media.id,
            expiresIn: 60 * 60 // One hour in seconds
          })
        } catch (e) {
          console.log('shamoon44', { e })
        }
      })

    })
    setActivePostIndex(0)
  }, [posts])
```

The `file` won't work

**Comment by dmitryame** [comment]
1. Why do you need to pre-load the images? Why don't you just reference these images on the screen using `CachedImage` tag -- it will handle loading, caching, rendering all by itself.
2. Any chance you can `console.log(media.id, media.url)` and post the output here?
3.  `expiresIn` is a property of the `CachedImage` tag -- if the image in the cache is older than then `expiresIn` value -- it will try to load it from the web again. It really does not make sense to apply this properly to the `CacheManager. addToCache` (well, at least, this is how it currently works). 

Hope it helps.

**Comment by shamoons** [comment]
1. I know the images that I’ll have to display later. On different screens. So I want to catch them all, before they are needed.

2. I’ll get you those logs shortly. 

3. If I add something to the CacheManager, wouldn’t it make sense to know how long it should be cached for?

**Comment by dmitryame** [comment]
3. The reason the `CacheManager.addToCache` was added to the library, as a way to override something that was already added to the cache by a specific key, regardless of how long ago it was added.  The item on the file system in cache has the time stamp when it was created, but it does not store the `expiresIn` anywhere. The `expiresIn` only says, if the file's been in the cache for that long or longer, at the time I try to access it -- remove it from cache and re-cache from the network again. I never thought of adding this `expiresIn` to `CacheManager. addToCache` as a parameter. `CacheManager. addToCache` is meant to force update the item in the cache.

**Comment by shamoons** [comment]
That makes sense - what about item 1? Preloading images so they're already in cache by the time they're needed?

**Comment by dmitryame** [comment]
Why do you care about expiring them? Are the images expected to change over time for any given key? If not, just stick them in the cache and let OS worry about cleaning out the temp space (this is where they are being cached).

**Comment by dmitryame** [comment]
One more thing i noticed, you are using `id`, the property should be `key`
```
 photo.getImgUrl = await CacheManager.addToCache({
    file: `${CONST.PENDING_UPLOADS_FOLDER}${item}`,
    key: `${photo.id}`,
  })
```

**Comment by dmitryame** [comment]
In this case you don't need to worry about expiration, just call unconditionally `CacheManager.addToCache`

**Comment by shamoons** [comment]
But I can’t specify a URL

**Comment by dmitryame** [comment]
Oh, I finally see what you are trying to do. In this case, can you just invoke the `CachedImage` as a function with parameters in `useEffect`? Something like this example: https://dev.to/igor_bykov/react-calling-functional-components-as-functions-1d3l

```
import CachedImage from 'expo-cached-image'
...


useEffect(() => {
  
posts.forEach((post) => {
      post.media_attachments.forEach(async (media) => {
        try {

  CachedImage(
    { source: { 
            uri: media.url,
            expiresIn: 2_628_288, // 1 month in seconds (optional), if not set -- will never expire and will be managed by the OS
            }, 
      cacheKey: media.id,
   }
)       
        } catch (e) {
          console.log('shamoon44', { e })
        }
      })

    })
    setActivePostIndex(0)

  }, [posts])


```

Something like this, you going to have to experiment with it in your code. Good luck -- it should be doable.

**Comment by shamoons** [comment]
Pretty good idea. But I get:
```
 [Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.]}
```

**Comment by shamoons** [comment]
I even extracted it to a separate hook:
```
import CachedImage from 'expo-cached-image'


export default function useCachedImage() {

  const preloadImage = (image) => {
    CachedImage({
      source: {
        uri: image.url,
        expiresIn: 60 * 60 // One hour in seconds
      },
      cacheKey: image.id
    })
  }

  return { preloadImage }
};
```

Which I then use:
```
const cachedImageHook = useCachedImage()
...

  useEffect(() => {
    posts.forEach((post) => {
      post.mediaAttachments.forEach(async (media) => {

        try {
          await cachedImageHook.preloadImage({ url: media.url, id: media.id })
        } catch (e) {
          console.log('shamoon44', { e })
        }
      })

    })
    setActivePostIndex(0)
  }, [posts])
```

**Comment by dmitryame** [comment]
So, it works for you? Is it OK to close the issue?

**Comment by shamoons** [comment]
No - not working. I get [this issue](https://github.com/echowaves/expo-cached-image/issues/18#issuecomment-1318796168)

**Comment by shamoons** [comment]
Alternatively, I'm happy to PR it to accept a `uri` in the `cacheManager`. Might be cleaner. Thoughts?

**Comment by dmitryame** [comment]
Just added to the latest version on npm(47.1.0):
```
  await CacheManager.downloadAsync({uri: `${item.url}`, key: `${item.id}`})
```
Please help me to test it, to make sure it works. 
Nothing fancy, it's just a convenience wrapper around  `FileSystem.downloadAsync`
Let me know if it works for you.

**Comment by shamoons** [comment]
Weird issue:

```
shamoon44 {"e": [Error: Unable to download file: Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={_NSURLErrorRelatedURLSessionTaskErrorKey=(
    "BackgroundDownloadTask <DAF42B19-C2F4-4B9C-B9F4-002E09D4E124>.<128>"
), NSLocalizedDescription=unsupported URL, _NSURLErrorFailingURLSessionTaskErrorKey=BackgroundDownloadTask <DAF42B19-C2F4-4B9C-B9F4-002E09D4E124>.<128>}]} https://s3.eu-central-2.wasabisys.com/mastodonworld/cache/media_attachments/files/109/360/168/493/358/770/original/3b721ea653cff115.jpeg
```

**Comment by dmitryame** [comment]
Just tested the following code -- works for me:
```
  const init = async () => {
    const returned = await CacheManager.downloadAsync({
      uri: `${photo.imgUrl}`,
      key: `${photo.photoUuid}`,
    })
    console.log({ returned })
  }
  useEffect(() => {
    init()
  }, [])

```

**Comment by shamoons** [comment]
Ahhh - I had `url`. It works now! Thanks so much!

**Comment by dmitryame** [comment]
@shamoons great that you were able to get it to work. 
I've been thinking about your use case. Just want to make sure you get the best out of this little library. 
If your users keep returning to the same images over and over again, it's best to just use `<CachedImage/>` tag and not worry about anything (you can add `placeholderContent` to show the progress indicator so that your users know they have to wait a little the first time around, but every time they open it again -- it's right there waiting for them). Another good approach is to show thumb image first (usually takes no time to download), I can share some examples if you do have the thumb images accessible via URL. 
Using `CacheManager.downloadAsync` will forcefully re-download the same file over and over again, which may create heavy network traffic. Again, totally up to you (depending on your use case), but wanted to share some thoughts.

**Comment by dmitryame** [comment]
I would actually be strongly advocating removing `CacheManager.downloadAsync` from the library completely, to avoid the wrong way of using it.
