### ISSUE TITLE
I have to reload the app to display the new images.

### ISSUE THREAD

**Issue by Alexis798** [echowaves/expo-cached-image#19]
Good afternoon, I had found this library and I installed it in my expo project and it worked well, but I have an issue, I use the function 'await CacheManager.downloadAsync({uri: `${item.url}`, key: `${item.id}`}', to preload the image, but when I edit the image and I go to the screen to see the picture the data is reload but the image don't changes I have to reload the complete project to see the image, is there any way to prereload the new image when user reload the data in the screen?

I hope I explained well the issue, sorry for the mistakes I speak Spanish.

**Comment by dmitryame** [comment]
Don't know what to tell you. This npm is rather simple and adding `CacheManager.downloadAsync` was a mistake -- I intend to remove it from the library eventually, because it's creates more confusion. 
No one should ever pre-load images -- just use the tag `<CachedImage />` and let it handle the timing. 
If contents of the image change, just use a different key –– that would be my advice.

**Comment by dmitryame** [comment]
And i do not understand what exactly you mean by "reload the app"? Do you mean you have to close the app and  start it again, and then it works? To me it seems you need to better understand the life cycle of react components. Seems that your component may not re-render.

**Comment by Alexis798** [comment]
Thank you for answer, well, I have used CacheManager.downloadAsync for preload because at the first time <CachedImage /> doesn't show any image, the placeholder stay loading, and about the re-render I used Flatlist with the RefreshControl, when I refresh the api fetch the new data and in consequence they key id change with the url but still shows the image before, so I have to close the app and start it again to show the new image but with the other images that doesn't use CachedImage changes.

**Comment by dmitryame** [comment]
> I have used CacheManager.downloadAsync for preload because at the first time doesn't show any image, the placeholder stay loading, but if I use that the image loaded at the first moment

It should work out of the box.
Take a look at how it's used in my project: https://github.com/echowaves/WiSaw/blob/master/src/components/Photo/PinchableView.js#L98
I actually first render the thumb image (because it loads very fast), then I render on top of that the full version of the image with the ActivityIndicator as placeholderContent.
Nothing fancy -- always works. 

If you can share some pointers to your code, I may be able to take a look.

**Comment by Alexis798** [comment]
first of all sorry for the next code, I am still learning react native and I did my first version with class, I know I have to change that to hooks, I am working on it, but here is some part of my code with class version.

> import React, {Component} from 'react'; 
import { View, Image, RefreshControl, Alert, Dimensions, Platform} from 'react-native';
import { NativeBaseProvider, Text, Heading, Spinner,  Stack, Slide, Alert as AlertNativeBase, VStack, HStack, Skeleton, Center, Divider } from 'native-base';
import globalStyles from '../styles/global';
import Card from '../shared/card';
import AsyncStorage from '@react-native-async-storage/async-storage';
import api from '../api/api';
import { FlatList } from 'react-native-gesture-handler';
import { StatusBar } from 'expo-status-bar';
import CachedImage, { CacheManager } from 'expo-cached-image'

import NetInfo from "@react-native-community/netinfo";

export default class Profile extends Component {
    NetInfoSubscription = null;

    constructor(props) {
        super(props);
        this.state = {
            //Variables
            email : '',
            perm : false,
            info : [],
            refreshing: false,

            //Internet Connection
            connection_status: false,
            connection_refreshStatus: false,
            clockrun : false,

            //LoadingFirstTime
            readyDisplay : false
        }
    }

    async componentDidMount(){
        this.NetInfoSubscription = NetInfo.addEventListener(this._handleConnectivityChange)

		//Get user profile
		let userLogin = await AsyncStorage.getItem('userLogin')
		userLogin = JSON.parse(userLogin)
		this.setState({ email : userLogin.email, perm : userLogin.perm})

        if(this.state.connection_status == true) {
            //Get user profile data
            let profile = await api.getProfile(this.state.email,this.state.perm)
            this.setState({ info : profile.data, loading : false, connection_refreshStatus: false})
            
            await Image.queryCache([this.state.info[0].phome]).then((res) => { console.log(res) });
            //Data for cache
            let cache = await AsyncStorage.getItem('profileCache')
            cache = JSON.parse(cache)
            if(JSON.stringify(cache) !== JSON.stringify(profile)) {
                await AsyncStorage.setItem('profileCache',JSON.stringify(profile))
            }

            await CacheManager.downloadAsync({uri: `${this.state.info[0].phome}`, key: `${this.state.info[0].phomeName}`})

        } else {
            //Data for cache
            let cache = await AsyncStorage.getItem('profileCache')
            cache = JSON.parse(cache)
            if(cache == null) {
                this.setState({connection_refreshStatus: true, loading : false, readyDisplay : true})
            } else {
                let profile = cache
                this.setState({ info : profile.data, loading : false, connection_refreshStatus: false})

                await CacheManager.downloadAsync({uri: `${this.state.info[0].phome}`, key: `${this.state.info[0].phomeName}`})
            }
            
        }

        //Autorefresh when focus the screen
		this._onFocusListener = this.props.navigation.addListener('focus', () => {
			this.onRefresh()
		});  

    }

    //Refresh function call
	onRefresh = () => {
        this.setState({ refreshing: true });
        this.refresh().then(() => {
            this.setState({ refreshing: false });
        });
    }    

    //Refresh function
    refresh = async() => {
        if(this.state.connection_status == true) {
            //Get user profile data
            let profile = await api.getProfile(this.state.email,this.state.perm)
            this.setState({ info : profile.data, loading : false, connection_refreshStatus: false})

            //Data for cache
            let cache = await AsyncStorage.getItem('profileCache')
            cache = JSON.parse(cache)
            if(JSON.stringify(cache) !== JSON.stringify(profile)) {
                await AsyncStorage.setItem('profileCache',JSON.stringify(profile))
            }

            await CacheManager.downloadAsync({uri: `${this.state.info[0].phome}`, key: `${this.state.info[0].phomeName}`})
            
        } else {
            //Data for cache
            let cache = await AsyncStorage.getItem('profileCache')
            cache = JSON.parse(cache)
            if(cache == null) {
                this.setState({connection_refreshStatus: true, loading : false, readyDisplay : true})
            } else {
                let profile = cache
                this.setState({ info : profile.data, loading : false, connection_refreshStatus: false})

                await CacheManager.downloadAsync({uri: `${this.state.info[0].phome}`, key: `${this.state.info[0].phomeName}`})
            }
        }
    }

    _handleConnectivityChange = (state) => {
        this.setState({ connection_status: state.isConnected, clockrun : true });
        this.Clock()
    }
    
    Clock = () => {
        this.timerHandle = setTimeout (() => {
          this.setState({clockrun : false});
          this.timerHandle = 0;
        }, 5000)
    }

    noInternetConnection = () => {
        Alert.alert('There is no internet connection, connect and try again.')
    }

    tryAgainNotConnection = () => {
        this.setState({clockrun : true})
        this.Clock()
    }
    
    componentWillUnmount(){
        this.NetInfoSubscription && this.NetInfoSubscription()
        clearTimeout(this.timerHandle)
        this.timerHandle = 0;
    }

    render() {
        return (
            <NativeBaseProvider>
				<StatusBar style="light" translucent={true} />
				<View>
				{this.state.readyDisplay == false && (
					<View style={globalStyles.skeletonMarginTop}>
                        <Center w="100%">
                            <VStack w="90%" borderWidth="1" space={6} rounded="md" alignItems="center" _dark={{borderColor: "coolGray.500"}} _light={{borderColor: "coolGray.200"}}>
                                <Skeleton h="40" />
                                <HStack space="2">
                                    <Skeleton.Text px="5" />
                                </HStack>
                                <VStack w="90%" borderWidth="1" space={8} overflow="hidden" rounded="md" _dark={{borderColor: "coolGray.500"}} _light={{borderColor: "coolGray.200"}}>
                                    <View style={globalStyles.skeletonMarginProfileText}>
                                        <HStack space="2" alignItems="center">
                                            <Skeleton size="5" rounded="full" />
                                            <Skeleton h="3" flex="2" rounded="full" />
                                        </HStack>
                                    </View>
                                    <Skeleton.Text px="5" />
                                    <Skeleton.Text px="5" my="4" />
                                </VStack>
                                {(Dimensions.get('window').width >= 414 && (Platform.isPad === true || Platform.OS === 'android')) && (
                                        <VStack w="90%" borderWidth="1" space={8} overflow="hidden" rounded="md" _dark={{borderColor: "coolGray.500"}} _light={{borderColor: "coolGray.200"}}>
                                            <View style={globalStyles.skeletonMarginProfileText}>
                                                <HStack space="2" alignItems="center">
                                                    <Skeleton size="5" rounded="full" />
                                                    <Skeleton h="3" flex="2" rounded="full" />
                                                </HStack>
                                            </View>
                                            <Skeleton.Text px="5" />
                                            <Skeleton.Text px="5" my="4" />
                                        </VStack>
                                    )}
                                <Skeleton px="4" my="4" rounded="md" startColor="purple.200" />
                            </VStack>
                        </Center>
                    </View>
				)}

				{this.state.readyDisplay == true && (
					<View>
					{this.state.connection_refreshStatus != false && (
						<View>
                            {this.state.refreshing == true && (
                                <View style={globalStyles.spinnerRefreshInternet}>
                                    <Spinner color="purple.500" style={ globalStyles.spinner} size="lg"/>
                                </View>
                            )}

						<Slide in={!this.state.clockrun ? false : true} placement="top">
							{this.state.connection_status ?
							<AlertNativeBase style={globalStyles.StacknoInternetConnection}  justifyContent="center" bg="emerald.100" >
								<VStack space={2} flexShrink={1} w="100%">
								<HStack flexShrink={1} space={2}  justifyContent="center">
									<Text color="emerald.600" fontWeight="medium">You are connected</Text>
								</HStack>
								</VStack>
							</AlertNativeBase>
							:
							<AlertNativeBase style={globalStyles.StacknoInternetConnection}  justifyContent="center" status="error">
								<VStack space={2} flexShrink={1} w="100%">
								<HStack flexShrink={1} space={2}  justifyContent="center">
									<Text color="error.600" fontWeight="medium">
									<AlertNativeBase.Icon />
									<Text> No Internet Connection</Text>
									</Text>
								</HStack>
								</VStack>
							</AlertNativeBase> 
							}
						</Slide>

						<View style={globalStyles.WelcomeImageMargin}>
							<Image 
							resizeMode="contain"
							source={require('../assets/img/empty/vacio-antena.png')}
							style={globalStyles.imageNotInternet} />
						</View>

						<View style={globalStyles.WelcomeTextandBoton}>
							<Heading size='sm'style={ globalStyles.tituloWelcome }>There is not internet connection.</Heading>
							<Heading size='sm'style={ globalStyles.tituloWelcome }>Connect to the internet and try again.</Heading>   
						</View>

						
                        <View>
                            <Text onPress={this.state.connection_status ? this.onRefresh : this.tryAgainNotConnection} style={globalStyles.createaccount}> Try Again </Text>
                        </View>
						</View>
					)}

					{this.state.connection_refreshStatus == false && (
						<View style={globalStyles.container}>
							<View>
								<Slide in={this.state.connection_status ? false : this.state.clockrun == false ? false : true} placement="top">
									<AlertNativeBase style={globalStyles.StacknoInternetConnection}  justifyContent="center" status="error">
									<VStack space={2} flexShrink={1} w="100%">
										<HStack flexShrink={1} space={2}  justifyContent="center">
											<Text color="error.600" fontWeight="medium">
											<AlertNativeBase.Icon />
											<Text> No Internet Connection</Text>
											</Text>
										</HStack>
									</VStack>
									</AlertNativeBase>
								</Slide>

								<FlatList 
                                    data={this.state.info}
                                    extraData={this.state.info}
                                    ListFooterComponent={() => this.state.loading ? <Spinner color="purple" style={ globalStyles.spinner2}/> : null}
                                    keyExtractor={item => `${item.info}`}
                                    nestedScrollEnabled={true}
                                    refreshControl={
                                        <RefreshControl
                                        enabled={true}
                                        refreshing={this.state.refreshing}
                                        onRefresh={this.onRefresh}
                                        tintColor="purple"
                                        colors={["purple","purple"]}
                                    />
                                    }
                                    renderItem={({item}) => (
                                        <View>
                                            <View style={ item.phome== "NULL" && item.pliving == "NULL" && item.parea1 == "NULL" && item.parea2 == "NULL" && item.parea3 == "NULL" && item.parea4 == "NULL" && item.pbath1 == "NULL" && item.pbath2 == "NULL" && item.pbath3 == "NULL" && item.pbath4 == "NULL" ? globalStyles.hideContents : globalStyles.show}>
                                                    <Card>
                                                            {/*Gallery*/}
                                                            <View>
                                                                {(Dimensions.get('window').width < 414 || (Platform.isPad != true && Platform.OS != 'android')) && (
                                                                    <Stack alignItems="center" width="100%">
                                                                        <HStack alignItems="center">
                                                                            <VStack width="90%">
                                                                                <View>
                                                                                <Heading size='md' style={ globalStyles.infomaintitleditNativeBase}>Gallery</Heading>
                                                                                </View>  
                                                                            </VStack>
                                                                            <Center size="12" width="10%">
                                                                                <Image
                                                                                    source={require("../assets/img/editIcons/gallery-16.png")}
                                                                                    resizeMode="contain"
                                                                                    style={globalStyles.editiconsNativeBase}
                                                                                />
                                                                            </Center>
                                                                        </HStack>
                                                                    </Stack>
                                                                )}
                                                                {(Dimensions.get('window').width >= 414 && (Platform.isPad === true || Platform.OS === 'android')) && (
                                                                    <Stack alignItems="center">
                                                                        <HStack alignItems="center">
                                                                            <Center width="20%">
                                                                            <View>
                                                                                <Heading size='md' style={ globalStyles.infomaintitleditNativeBase}>Gallery</Heading>
                                                                            </View> 
                                                                            </Center>
                                                                            <Center size="12">
                                                                            <Image
                                                                                    source={require("../assets/img/editIcons/gallery-16.png")}
                                                                                    resizeMode="contain"
                                                                                    style={globalStyles.editiconsNativeBase}
                                                                            />
                                                                            </Center>
                                                                        </HStack>
                                                                    </Stack>
                                                                )}

                                                                {/*PHOTO HOME */}
                                                                <View style={item.phome == "NULL" ? globalStyles.hideContents : globalStyles.showphoto}>
                                                                    <Card style={item.phome == "NULL" ? globalStyles.hide : globalStyles.shadowbox}>
                                                                        <Heading size='lg' style={ item.phome == "NULL" ? globalStyles.hide : globalStyles.infotitle2 }>Frontage</Heading>
                                                                        <Divider my="2" bg="gray.500"/>
                                                                        <CachedImage
                                                                            source={{ 
                                                                            uri: `${item.phome}`, // (required) -- URI of the image to be cached
                                                                            headers: `Authorization: Bearer ${token}`, // (optional)            
                                                                            expiresIn: 2_628_288, // 1 month in seconds (optional), if not set -- will never expire and will be managed by the OS
                                                                            }}
                                                                            cacheKey={`photo-${item.phomeName}`} // (required) -- key to store image locally
                                                                            placeholderContent={( // (optional) -- shows while the image is loading
                                                                                <Spinner color="purple" style={ globalStyles.spinner2}/> 
                                                                            )} 
                                                                        />
                                                                    </Card>
                                                                </View>

                                                                {/*PHOTO LIVING ROOM */}
                                                                <View style={item.pliving == "NULL" ? globalStyles.hideContents : globalStyles.showphoto}>
                                                                    <Card style={item.pliving == "NULL" ? globalStyles.hide : globalStyles.shadowbox}>
                                                                    <Heading size='lg' style={ item.pliving == "NULL" ? globalStyles.hide : globalStyles.infotitle2 }>Living Room</Heading>
                                                                        <Divider my="2" bg="gray.500"/>
                                                                        <Image
                                                                            source={{ uri: `${item.pliving}` }}
                                                                            resizeMode="contain"
                                                                            style={item.pliving == "NULL" ? globalStyles.hide : globalStyles.imageprofile}
                                                                        ></Image>
                                                                    </Card>
                                                                </View>	
					
                                                            </View>
                                                    </Card>
                                                </View>

                                        </View>
                                    )}
                                />
								</View>
							</View>
					)}
					</View>
				)}
				</View>
			</NativeBaseProvider>
        )
    }
}

**Comment by dmitryame** [comment]
Hey, no need to apologize -- we've all had to start somewhere, you are doing great.
You certainly should consider switching to hooks. Unrelated, but, if you paid for your react-native class -- ask for money back -- they should not be teaching you outdated tech which has no future.

Now, about your code. I noticed, in few places you have `==` comparison. Should it be `===` instead? This is very JS specific and honestly, while programming in JS, I have never came across a use case which required me to use `==` for comparison.

**Comment by dmitryame** [comment]
also, hard for me to say what your are trying to achieve, perhaps I'm completely wrong, but, if you think that your component will re-render and the image will show up after   the following line executes inside `componentDidMount`, you may need to spend some more time on learning the life cycle of react-native:
```
await CacheManager.downloadAsync({uri: `${this.state.info[0].phome}`, key: `${this.state.info[0].phomeName}`})
```


Don't mean to sound discouraging, but, if you are serious about using react-native -- you have to invest and there is no easy way out -- it's all sweat and tears my friend.

To learn and figure out what's going on, first, stop using the `CacheManager.downloadAsync`, 
instead, focus on using `<CachedImage />` out of the box. Try to experiment with `expiresIn` -- make it 0 to force expiration  and see if the component re-renders properly when the contents of the image change (see if it re-polls the image).
Then try to use something different for `placeHolder`, for instance just use `<Text>loading</Text>`
Your goal is to learn how the dots connect -- eliminate complexity, start simple, and once you get the concept to work you can add the  complexity back as needed one step at a time.

Hope it helps. Good luck!

**Comment by dmitryame** [comment]
Just try `expiresIn = 0` to see if that re-downloads the image for troubleshooting purpose to learn how the component lifecycle works. Try it in your dev, but don't release it in prod.

**Comment by dmitryame** [comment]
It means it can't download the image over the net for some reason.

**Comment by vbylen** [comment]
This is what I did:

```jsx
import CachedImage from 'expo-cached-image'

const ImageWrapper = (rest) => {
  //increment the key to re-render
  const [key = 12345, setKey] = useMMKVNumber('avatar.key')

  return <CachedImage {...rest} key={key} />
}

export { ImageWrapper as Image, CacheManager }
```

So when I'm uploading  a new profile picture for example all I need to do is:

```jsx
await CacheManager.addToCache({
  file: images[0]?.uri,
  key: profile?.id,
  })
let i = key + 1
setKey(i)
```

It's a hacky solution but it works for me.

Love the elegance and speed of this library btw. Thanks for making it!
