### ISSUE TITLE
Type declaration file

### ISSUE THREAD

**Issue by ansh** [echowaves/expo-cached-image#21]
Please add a type declaration file!

**Comment by ansh** [comment]
I see there was an issue opened for this #2 and since then a .d.ts file was added to the repo but unfortunately it seems like the .d.ts file does not show up when the package is installed from `npm` 
<img width="271" alt="CleanShot 2022-12-14 at 02 17 28@2x" src="https://user-images.githubusercontent.com/8207733/207440344-622b726c-7ba9-4bf6-9137-4d4c5a617ff4.png">

**Comment by ansh** [comment]
I have rewritten this package in TypeScript. I can share it here if interested.

**Comment by dmitryame** [comment]
yeah, sure, send the pull request please — i’d be happy to consider merging it to the mainSent from my iPhoneOn Dec 14, 2022, at 11:00, Ansh ***@***.***> wrote:﻿
I have rewritten this package in TypeScript. I can share it here if interested.

**Comment by SaltMango** [comment]
> I have rewritten this package in TypeScript. I can share it here if interested.

Can you share it?

**Comment by dmitryame** [comment]
@ansh any updates?

**Comment by finnp** [comment]
This is what I've been using, but I'm only specifying the `cacheKey`. Other property and the cache manager would still need to be added.

```ts
declare module 'expo-cached-image' {
  import {ImageProps} from 'react-native';

  type CachedImageProps = ImageProps & {
    cacheKey?: string
  }

  export default function (props: CachedImageProps): JSX.Element;
}
```

**Comment by dmitryame** [comment]
Guys, I'm not a typescript expert, if someone wants to send me a working PR, I can review and merge it into the main line.
