### ISSUE TITLE
CacheManager.downloadAsync is not a function

### ISSUE THREAD

**Issue by Bijig0** [echowaves/expo-cached-image#22]
Not sure what's going on. I'm trying to load images from a remote url at the top of my app with the below code and im getting a warning that `CacheManager.downloadAsync` is not a function`.

```js
const useAppIsReady = async (data) => {
  ...
  await CacheManager.downloadAsync({ uri: "google.com", key: "snafwiofhawi" });
  ...
}
```

```
Possible Unhandled Promise Rejection (id: 643):
TypeError: _expoCachedImage.CacheManager.downloadAsync is not a function. (In '_expoCachedImage.CacheManager.downloadAsync({   
        uri: "google.com",
        key: "snafwiofhawi"
      })', '_expoCachedImage.CacheManager.downloadAsync' is undefined)
@
```

**Comment by dmitryame** [comment]
How do you import it into your src?
Like this?
```
import { CacheManager } from 'expo-cached-image'
```

**Comment by Bijig0** [comment]
`import { CacheManager } from "expo-cached-image";`

Yeah. Im using version 46.0.1 tho so ill try go to the latest version and see what happens

**Comment by dmitryame** [comment]
did it work for you? Can this issue be closed?
