### ISSUE TITLE
Images are not shwing on IOS in offline mode.

### ISSUE THREAD

**Issue by zainulhasan** [echowaves/expo-cached-image#24]
Hello, 
Thanks for the amazing package. This is a time saver. I am having a little issue. I am preloading the image using
  await CacheManager.downloadAsync({uri: `${item.url}`, key: `${item.id}`})

and I am using <CachedImage  /> it to show images. On Android it works in offline mode as well but on iOS event images are there it only shows the placeholder. when I put the device online it starts showing the Images.  

Is there anything that I am missing?

**Comment by dmitryame** [comment]
hmmm, seems it works as expected, if the phone is in offline mode, it's not going to be able to download the image. You may want to add some network check and try to pre-load images only when the network is available.
