### ISSUE TITLE
Clear whole cache

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [echowaves/expo-cached-image#3]
Is it planned, that the CacheManager gets the possibility to clear the whole cache?

**Comment by dmitryame** [comment]
I was thinking about it, but, wouldn't it defeat the purpose of cache if you clear it all? The cached items lifecycle is managed by the OS mechanics implemented in expo-file-system, so if the fs start running low on space -- the OS will do the right job and clear out the old junk. I can consider adding the "clear all" method if you can describe a legit use case for it.

**Comment by mariomurrent-softwaresolutions** [comment]
You are totally right, but sometimes for development purposes this might be helpful. Or if you want to clear the cache, because newer data would be available after the app update. Instead of changing the caching keys.

**Comment by dmitryame** [comment]
The way i deal with it, either reinstall the app, which will clear the cache, or append a unique suffix to the key.

**Comment by mariomurrent-softwaresolutions** [comment]
Sounds like a plan
