### ISSUE TITLE
Image don't show up after update to SDK version 51 on ios

### ISSUE THREAD

**Issue by yann86** [echowaves/expo-cached-image#31]
Every things worked good with SDK 49 but after updating to SDK 51 the image is loaded but does show on ios.

**Comment by dmitryame** [comment]
Have you tried to upgrade to the latest version of expo-cached-image?

**Comment by sprutner** [comment]
This should resolve it https://github.com/echowaves/expo-cached-image/pull/33

**Comment by dmitryame** [comment]
thanks
