### ISSUE TITLE
Error loading image: Error: Calling the 'downloadAsync' function has failed

### ISSUE THREAD

**Issue by MarcoRettoreDev** [echowaves/expo-cached-image#35]
Hello there, im triying to use the library on my expo project. This is my implementation:

`const ImageWrapper: FC<Props> = ({
  id,
  style,
  source,
  contentFit = "cover",
}) => {
  return ( 
    <CachedImage
      source={{
        uri: source, 
      }}
      cacheKey={`${id}-image`} 
      placeholderContent={
        <ActivityIndicator 
          color={tw.color("blueSoft")}
          size="small"
          style={{
            flex: 1,
            justifyContent: "center",
          }}
        />
      }
      resizeMode={contentFit} 
      style={style}
    />
  );
};`

And this is the error im getting:

![image](https://github.com/user-attachments/assets/f3f171ac-7d1f-4890-9cac-a19696ff0f9b)

Thing that i already checked:

- Styles
- Diferents keys
- No placeholderContent

I also have to say that i'm able to render those images throught the Image component from Expo, so there is no header or token to access them (they are public)

Versions:
"@react-native-async-storage/async-storage": "1.23.1",
"expo": "~51.0.28",
"expo-cached-image": "^51.0.19",
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native": "0.74.5",

Thank you so much for your work, i would be great if we could fix this issue

**Comment by dmitryame** [comment]
hmm, have checked the source code -- there are no any references to URL in the code. Have you tried to hard code the value of the uri to see if it works?

**Comment by dmitryame** [comment]
Another thought, can you try to pass uri source as a string, something like this:
``` 
source={{ uri: `${source}`,  }} 
```

Let me know if it solves your issue.

**Comment by MarcoRettoreDev** [comment]
Sorry i was passing the wrong prop to the source of <CachedImage> ... 
i was passing and object like: {uri: source}
when only the string of the url was needed.. i'll close this
Thanks for helping 👍🏽
