### ISSUE TITLE
Still relevant

### ISSUE THREAD

**Issue by ScreamZ** [echowaves/expo-cached-image#9]
Is it still relevant now that FastImage is compatible with EAS build and managed ?

 (even though fast image precache is not working well)

**Comment by dmitryame** [comment]
I think it's still relevant. It's pure react-native implementation and no platform specific code in it. Very simple, light weight, still offers flexibility for loading indicator and cache expiration etc... So, yes -- it still holds it's value :)

**Comment by dmitryame** [comment]
But feel free to share your thoughts.

**Comment by ScreamZ** [comment]
Yeah, it's pure JS that is true and nice.

I ended up here reading your article about https://www.echowaves.com/post/expo-filesystem-cachedirectory-has-to-be-cleaned

And browsing this library give me some nice advice for such a use case. For now, I was using fast-images but I'm looking for the caching mechanism because i Also need to cache video assets and this looks great.
